/**
 * PARTIE B — CONSOMMABLES & STOCK (Codes 6xx)
 * Source : ANNEXE_NOMACT_SIGNE.PDF
 * Type : Consommables → suivi en QUANTITÉ uniquement (PAS d'ID individuel)
 * Usage : Module Stock uniquement
 */

export interface StockItem {
  code: string;
  intitule: string;
}

export interface StockGroupe {
  compte: string;
  libelle: string;
  categorie: string;
  famille: string;
  type_bien: "consommable" | "entretien";
  unite_defaut: string;
  items: StockItem[];
}

export const PARTIE_B_STOCK: StockGroupe[] = [
  // ─────────────────────────────────────────────────────────────────────────
  // 601 — MATIÈRES, MATÉRIELS ET FOURNITURES
  // ─────────────────────────────────────────────────────────────────────────
  {
    compte: "601",
    libelle: "MATIÈRES, MATÉRIELS ET FOURNITURES",
    categorie: "Fournitures de bureau",
    famille: "Papeterie et consommables bureau",
    type_bien: "consommable",
    unite_defaut: "pièce",
    items: [
      { code: "601.001", intitule: "Agenda" },
      { code: "601.002", intitule: "Agrafe" },
      { code: "601.003", intitule: "Agrafeuse" },
      { code: "601.004", intitule: "Anneaux" },
      { code: "601.005", intitule: "Ardoise en carton" },
      { code: "601.006", intitule: "Attache" },
      {
        code: "601.007",
        intitule:
          "Baguettes de reliure de 3, 6 et 12 (paquet de 25, 26 et 28)",
      },
      { code: "601.008", intitule: "Bande Machine à calculer" },
      { code: "601.009", intitule: "Bloc note" },
      { code: "601.010", intitule: "Bloc post-it (GM, MM, PM)" },
      { code: "601.011", intitule: "Boîte archive" },
      { code: "601.012", intitule: "Cahier" },
      { code: "601.013", intitule: "Calculatrice" },
      { code: "601.014", intitule: "Carbone à machine et main" },
      {
        code: "601.015",
        intitule: "Carnet de note de 100 et 200 pages (Paquet de 10)",
      },
      {
        code: "601.016",
        intitule:
          "Carnet de reçu standard en feuilles sur papier chimique (10 carnets de 100 feuillets de paquet de 10)",
      },
      {
        code: "601.017",
        intitule: "Carnet de comptes de gestion de 100 feuilles format A4",
      },
      {
        code: "601.018",
        intitule:
          "Carnet de conformité 100 feuillets 50 originales et 50 souches autocopions quantité 100 et format demi-commercial",
      },
      {
        code: "601.019",
        intitule: "Carnet structure de facturier de 100 feuilles",
      },
      { code: "601.020", intitule: "Cartable en plastique" },
      {
        code: "601.021",
        intitule: "Carton de papier rame A4 (Carton de 5)",
      },
      {
        code: "601.022",
        intitule: "Cartouche d'encre copieur (boîte de 1 ou 2 tubes)",
      },
      { code: "601.023", intitule: "Cartouche d'encre copieur ricoh toner" },
      { code: "601.024", intitule: "Chemise à sangle / ordinaire/ à rabat" },
      {
        code: "601.025",
        intitule: "Chemise/Sous-chemise (paquet de 250)",
      },
      { code: "601.026", intitule: "Chemise pochette de 9 perforateurs" },
      { code: "601.027", intitule: "Ciseau paire" },
      { code: "601.028", intitule: "Classeur" },
      { code: "601.029", intitule: "Colle liquide" },
      { code: "601.030", intitule: "Compas pour tableau" },
      { code: "601.031", intitule: "Corbeille de bureau" },
      {
        code: "601.032",
        intitule: "Correcteur blanco à bille / avec diluant",
      },
      {
        code: "601.033",
        intitule: "Couverture cristal et cuir (paquet de 100)",
      },
      {
        code: "601.034",
        intitule: "Craie blanche et couleur (carton de 16)",
      },
      { code: "601.035", intitule: "Crayon à papier (paquet de 12)" },
      { code: "601.036", intitule: "Criterium (mine)" },
      { code: "601.037", intitule: "Cutter GM" },
      { code: "601.038", intitule: "Dateur" },
      { code: "601.039", intitule: "Désagrafeuses" },
      {
        code: "601.040",
        intitule: "Dévidors coupe scotch (GM, PM)",
      },
      { code: "601.041", intitule: "Enveloppe" },
      { code: "601.042", intitule: "Éphéméride" },
      { code: "601.043", intitule: "Équerre" },
      { code: "601.044", intitule: "Ficelle bureau GM" },
      { code: "601.045", intitule: "Ficelle d'emballage PM" },
      { code: "601.046", intitule: "Gomme" },
      { code: "601.047", intitule: "Info Note GM, MM, PM" },
      { code: "601.048", intitule: "Marqueur" },
      { code: "601.049", intitule: "Mine Critérium" },
      { code: "601.050", intitule: "Mouilleur" },
      {
        code: "601.051",
        intitule: "Papier Rame A4 double A (carton de 5)",
      },
      { code: "601.052", intitule: "Papier Fax" },
      { code: "601.053", intitule: "Papier Pelure (paquet de 5)" },
      { code: "601.054", intitule: "Papier Rame A3 (rame de 500)" },
      { code: "601.055", intitule: "Papier Repro (rame de 500)" },
      { code: "601.056", intitule: "Papier rame double A" },
      { code: "601.057", intitule: "Papier calque" },
      { code: "601.058", intitule: "Papier calque format A4 (pochette de 12)" },
      { code: "601.059", intitule: "Papier calque mètre" },
      { code: "601.060", intitule: "Papier (filme et à plastifier)" },
      { code: "601.061", intitule: "Parapheur" },
      { code: "601.062", intitule: "Perforateur" },
      { code: "601.063", intitule: "Porte bic bureau" },
      { code: "601.064", intitule: "Porte cachet" },
      { code: "601.065", intitule: "Pot de colle stick" },
      { code: "601.066", intitule: "Punaise" },
      { code: "601.067", intitule: "Registre" },
      {
        code: "601.068",
        intitule: "Règle (écolière plate, plate tableau)",
      },
      { code: "601.069", intitule: "Réglette" },
      { code: "601.070", intitule: "Spiral" },
      { code: "601.071", intitule: "Stylos" },
      { code: "601.072", intitule: "Stylos Feutre marqueur" },
      { code: "601.073", intitule: "Stylos Pilote" },
      { code: "601.074", intitule: "Surligneur" },
      { code: "601.075", intitule: "Taille crayon à poubelle" },
      { code: "601.076", intitule: "Transparent porte document" },
      { code: "601.077", intitule: "Tube d'encre Rouge à tampon" },
      { code: "601.078", intitule: "Vernis correcteur blanc habille" },
      {
        code: "601.079",
        intitule:
          "Fournitures de petits matériels de bureau, de produits d'entretien et de charroi",
      },
      {
        code: "601.080",
        intitule: "Bordereau de livraison 03 feuilles x 50 auto copiant",
      },
      {
        code: "601.081",
        intitule: "Brouillard de caisse (recettes, dépenses, solde)",
      },
      { code: "601.082", intitule: "Bulletin de service" },
      { code: "601.083", intitule: "Bulletin individuel de note" },
      {
        code: "601.084",
        intitule: "Carte de remerciement A5 quadrier sur toile",
      },
      {
        code: "601.085",
        intitule: "Carte de visite lot de 100 sur papier toile 250p couleur",
      },
      { code: "601.086", intitule: "Cachet" },
      { code: "601.087", intitule: "Carnet en paquet" },
      {
        code: "601.088",
        intitule: "Carnet (Document de gestion du matériel, entrée-sortie)",
      },
      // Fournitures informatiques
      { code: "601.089", intitule: "Adaptateur" },
      { code: "601.090", intitule: "Alimentation" },
      {
        code: "601.091",
        intitule:
          "Antivirus (1, 2 et 10 postes avec 1 an de protection)",
      },
      { code: "601.092", intitule: "Barrette mémoire" },
      { code: "601.093", intitule: "Batterie carte mère" },
      { code: "601.094", intitule: "Batterie rechargeable" },
      { code: "601.095", intitule: "Belkin house Néoprène" },
      { code: "601.096", intitule: "Bluetooth" },
      { code: "601.097", intitule: "Boîte de lingettes" },
      {
        code: "601.098",
        intitule: "Boîte de CD vierge sans ou avec pochette",
      },
      {
        code: "601.099",
        intitule: "Boîte de DVD vierge sans ou avec pochette",
      },
      {
        code: "601.100",
        intitule: "Boîte de pochette de CD/DVD vierge",
      },
      { code: "601.101", intitule: "Boitier" },
      { code: "601.102", intitule: "Bombe à air" },
      {
        code: "601.103",
        intitule: "Câble (réseau catégorie, USB pour imprimante)",
      },
      { code: "601.104", intitule: "Câble (autres)" },
      { code: "601.105", intitule: "Carte" },
      { code: "601.106", intitule: "Cartouche d'encre/Toner" },
      {
        code: "601.107",
        intitule: "Casque avec ou sans microphone (PF, GM)",
      },
      { code: "601.108", intitule: "CD/DVD" },
      { code: "601.109", intitule: "CD-R / DVD-R" },
      {
        code: "601.110",
        intitule: "Chargeur (Batterie, IPOD, MP4, Universel mobile)",
      },
      { code: "601.111", intitule: "Clavier" },
      { code: "601.112", intitule: "Clé (USB, Wifi)" },
      { code: "601.113", intitule: "Convertisseur disk dur" },
      { code: "601.114", intitule: "Cooler to laptop" },
      {
        code: "601.115",
        intitule: "Couverture (pour Iphone et pour ordinateur)",
      },
      { code: "601.116", intitule: "Disque dur externe" },
      { code: "601.117", intitule: "Écouteur" },
      { code: "601.118", intitule: "Écran plat" },
      { code: "601.119", intitule: "Écran pour vidéo projecteur" },
      {
        code: "601.120",
        intitule: "Externe batterie pour Iphone & Samsung 400H",
      },
      { code: "601.121", intitule: "Graveur CD ROM interne et externe" },
      { code: "601.122", intitule: "Graveur DVD" },
      { code: "601.123", intitule: "Haut-parleur" },
      { code: "601.124", intitule: "HUB USB" },
      { code: "601.125", intitule: "Lecteur carte SD/DVD" },
      {
        code: "601.126",
        intitule: "Mousse (à nettoyage, nettoyante antistatique)",
      },
      { code: "601.127", intitule: "Multiprise" },
      { code: "601.128", intitule: "Outils pince" },
      { code: "601.129", intitule: "Photo pour Laptot" },
      {
        code: "601.130",
        intitule: "Pochette d'appareil photo numérique",
      },
      { code: "601.131", intitule: "Processeur" },
      { code: "601.132", intitule: "Protecteur pour clavier et écran" },
      { code: "601.133", intitule: "Ruban" },
      { code: "601.134", intitule: "Sac ordinateur portatif" },
      { code: "601.135", intitule: "Sacoche mallette/standard" },
      { code: "601.136", intitule: "Son/Enceintes" },
      { code: "601.137", intitule: "Souffleur (air sec, mini USB)" },
      { code: "601.138", intitule: "Tapis souris" },
      { code: "601.139", intitule: "Testeur réseau" },
      { code: "601.140", intitule: "Tools HDD" },
      { code: "601.141", intitule: "USB IDE à sata" },
      { code: "601.142", intitule: "USB lamp" },
      { code: "601.143", intitule: "Valise maintenance" },
      { code: "601.144", intitule: "Ventilo de processeur" },
      { code: "601.145", intitule: "Web camera" },
      // Fournitures téléphoniques
      { code: "601.146", intitule: "Casque téléphonique" },
      { code: "601.147", intitule: "Combiné téléphonique" },
      { code: "601.148", intitule: "Câble téléphonique" },
      { code: "601.149", intitule: "Autres fournitures téléphoniques" },
      // Carburants et lubrifiants
      { code: "601.150", intitule: "Carburant (super sans plomb/gaz oïl)" },
      { code: "601.151", intitule: "Graisse" },
      { code: "601.152", intitule: "Huile ATF" },
      { code: "601.153", intitule: "Huile à boîte" },
      { code: "601.154", intitule: "Huile hydraulique" },
      { code: "601.155", intitule: "Huile à moteur" },
      { code: "601.156", intitule: "Huile à pont" },
      { code: "601.157", intitule: "Huile à suspension" },
      { code: "601.158", intitule: "Liquide frein" },
      { code: "601.159", intitule: "Liquide lave glace" },
      { code: "601.160", intitule: "Liquide refroidissement" },
      { code: "601.161", intitule: "Vidange liquide" },
      // Valeurs et imprimés
      { code: "601.162", intitule: "Ticket" },
      { code: "601.163", intitule: "Timbre" },
      { code: "601.164", intitule: "Autres valeurs inactives" },
      { code: "601.165", intitule: "Déclaration de recette" },
      { code: "601.166", intitule: "Journal à souche" },
      { code: "601.167", intitule: "Dictionnaire" },
      { code: "601.168", intitule: "Journal presse écrite" },
      // Alimentation
      { code: "601.169", intitule: "Amuse-gueule en bouteille" },
      { code: "601.170", intitule: "Arômes" },
      { code: "601.171", intitule: "Boisson en canettes / bouteille plastique" },
      { code: "601.172", intitule: "Boisson-Jus" },
      { code: "601.173", intitule: "Boisson-eau" },
      { code: "601.174", intitule: "Beurre" },
      { code: "601.175", intitule: "Cacao en poudre" },
      { code: "601.176", intitule: "Café instantané" },
      {
        code: "601.177",
        intitule: "Céréales (Maïs, Mil, Sorgho, Riz, etc.)",
      },
      {
        code: "601.178",
        intitule: "Conserve (sardine, corned-beef, tomate, etc.)",
      },
      { code: "601.179", intitule: "Huile" },
      { code: "601.180", intitule: "Lait" },
      { code: "601.181", intitule: "Liqueur" },
      { code: "601.182", intitule: "Mayonnaise" },
      { code: "601.183", intitule: "Olives" },
      { code: "601.184", intitule: "Œufs" },
      { code: "601.185", intitule: "Poissons frais" },
      { code: "601.186", intitule: "Rehausseur de goût (cube)" },
      { code: "601.187", intitule: "Pâte alimentaire" },
      { code: "601.188", intitule: "Viande (bœuf, mouton, etc.)" },
      { code: "601.189", intitule: "Sucre en morceau" },
      { code: "601.190", intitule: "Sucre en poudre" },
      { code: "601.191", intitule: "Moutarde" },
      // Intrants agricoles
      { code: "601.192", intitule: "Engrais" },
      { code: "601.193", intitule: "Semence en graines" },
      { code: "601.194", intitule: "Semence en plantes" },
      { code: "601.195", intitule: "Blé" },
      { code: "601.196", intitule: "Fonio" },
      { code: "601.197", intitule: "Maïs" },
      { code: "601.198", intitule: "Riz" },
      { code: "601.199", intitule: "Sorgho" },
      {
        code: "601.200",
        intitule: "Autres matières, matériel et fournitures stockables",
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 605 — EAU, ÉLECTRICITÉ, GAZ ET AUTRES SOURCES D'ÉNERGIE
  // ─────────────────────────────────────────────────────────────────────────
  {
    compte: "605",
    libelle: "EAU, ÉLECTRICITÉ, GAZ ET AUTRES SOURCES D'ÉNERGIE",
    categorie: "Énergie et fluides",
    famille: "Sources d'énergie",
    type_bien: "consommable",
    unite_defaut: "unité",
    items: [
      { code: "605.001", intitule: "Gaz" },
      { code: "605.099", intitule: "Autres sources d'énergie" },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 606 — MATÉRIELS ET FOURNITURES SPÉCIFIQUES
  // ─────────────────────────────────────────────────────────────────────────
  {
    compte: "606",
    libelle: "MATÉRIELS ET FOURNITURES SPÉCIFIQUES",
    categorie: "Fournitures spécifiques",
    famille: "Médical et technique",
    type_bien: "consommable",
    unite_defaut: "pièce",
    items: [
      { code: "606.001", intitule: "Alcool" },
      { code: "606.002", intitule: "Anuscope" },
      { code: "606.003", intitule: "Bande" },
      { code: "606.004", intitule: "Bassin de lit" },
      { code: "606.005", intitule: "Blouse" },
      {
        code: "606.006",
        intitule:
          "Bock à lavement pic avec canules rectale et vaginale",
      },
      { code: "606.007", intitule: "Ciseaux" },
      { code: "606.008", intitule: "Compresse (stérile ou non)" },
      { code: "606.009", intitule: "Coton" },
      { code: "606.010", intitule: "Crachoir" },
      { code: "606.011", intitule: "Désinfection des instruments médicaux" },
      { code: "606.012", intitule: "Désinfection des surfaces et des sols" },
      { code: "606.013", intitule: "Désinfection du linge" },
      { code: "606.014", intitule: "Désinfection par voie aérienne" },
      { code: "606.015", intitule: "Lingette nettoyante et désinfectante" },
      { code: "606.016", intitule: "Distributeur de savon, de gel" },
      { code: "606.017", intitule: "Gant" },
      { code: "606.018", intitule: "Marteaux à reflexe" },
      { code: "606.019", intitule: "Masque médicaux ou chirurgicaux" },
      { code: "606.020", intitule: "Pansement" },
      { code: "606.021", intitule: "Pince" },
      { code: "606.022", intitule: "Plateaux" },
      { code: "606.023", intitule: "Seringue" },
      { code: "606.024", intitule: "Sonde" },
      { code: "606.025", intitule: "Sparadrap" },
      {
        code: "606.026",
        intitule: "Spray, tampons, sérum physiologique",
      },
      { code: "606.027", intitule: "Tablier" },
      { code: "606.028", intitule: "Urinal femme et homme" },
      {
        code: "606.029",
        intitule: "Fournitures et produits médicaments et vétérinaire",
      },
      { code: "606.030", intitule: "Vaccins" },
      { code: "606.031", intitule: "Déparasitant" },
      { code: "606.032", intitule: "Fourniture pour la radio" },
      { code: "606.033", intitule: "Fourniture pour la télévision" },
      // Fournitures topographiques
      { code: "606.034", intitule: "Barre à mine" },
      {
        code: "606.035",
        intitule: "Boite de peinture survinil rouge",
      },
      { code: "606.036", intitule: "Botte" },
      { code: "606.037", intitule: "Calque canson 90g A4" },
      { code: "606.038", intitule: "Calque satin rouleau" },
      { code: "606.039", intitule: "Canne 2,15m" },
      { code: "606.040", intitule: "Canne télescopique" },
      { code: "606.041", intitule: "Casque" },
      { code: "606.042", intitule: "Chaine de 50m/100m" },
      { code: "606.043", intitule: "Chaine en acier Pythagoras" },
      { code: "606.044", intitule: "Compas de précision" },
      { code: "606.045", intitule: "Cône" },
      { code: "606.046", intitule: "Coupe-coupe" },
      { code: "606.047", intitule: "Encre de chine noir" },
      { code: "606.048", intitule: "Équerre" },
      { code: "606.049", intitule: "Essence de Térébenthine" },
      { code: "606.050", intitule: "Fer à béton de 16 Tor 104/T" },
      { code: "606.051", intitule: "Gilets" },
      { code: "606.052", intitule: "GPS" },
      { code: "606.053", intitule: "Jalon 1m" },
      {
        code: "606.054",
        intitule: "Jeu 3 pinceaux BI matière 514697JP",
      },
      {
        code: "606.055",
        intitule: "Jeu de 6 instruments de mesures 45200",
      },
      { code: "606.056", intitule: "Marteau" },
      { code: "606.057", intitule: "Masse manche bois 5kg" },
      { code: "606.058", intitule: "Mire télescopique" },
      { code: "606.059", intitule: "Papier calque" },
      { code: "606.060", intitule: "Papier rouleau ordinaire" },
      { code: "606.061", intitule: "Plume" },
      { code: "606.062", intitule: "Plumes notring isographe" },
      { code: "606.063", intitule: "Pointe de canne" },
      { code: "606.064", intitule: "Profils en travers, par profil" },
      { code: "606.065", intitule: "Quiche" },
      { code: "606.066", intitule: "Rapporteur" },
      { code: "606.067", intitule: "Réflecteur" },
      { code: "606.068", intitule: "Rouleau papier caque" },
      { code: "606.069", intitule: "Théodolite" },
      { code: "606.070", intitule: "Petits matériels pédagogiques" },
      { code: "606.071", intitule: "Fourniture de matériel technique" },
      {
        code: "606.072",
        intitule: "Fournitures de géniteurs et d'alevins",
      },
      { code: "606.073", intitule: "Fournitures de provendes" },
      {
        code: "606.074",
        intitule: "Fournitures de boutures racinées, cabosses de cacao",
      },
      {
        code: "606.999",
        intitule: "Autres matériels et fournitures spécifiques",
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 607 — ACHAT DE MARCHANDISES
  // ─────────────────────────────────────────────────────────────────────────
  {
    compte: "607",
    libelle: "ACHAT DE MARCHANDISES",
    categorie: "Marchandises",
    famille: "Achats de marchandises",
    type_bien: "consommable",
    unite_defaut: "pièce",
    items: [
      { code: "607.001", intitule: "Achat de marchandises" },
      { code: "607.999", intitule: "Autres achats de marchandises" },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 609 — AUTRES ACHATS DE BIENS
  // ─────────────────────────────────────────────────────────────────────────
  {
    compte: "609",
    libelle: "AUTRES ACHATS DE BIENS",
    categorie: "Autres achats",
    famille: "Achats divers",
    type_bien: "consommable",
    unite_defaut: "pièce",
    items: [{ code: "609.999", intitule: "Autres achats de biens" }],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 614 — ENTRETIEN, RÉPARATION ET MAINTENANCE
  // ─────────────────────────────────────────────────────────────────────────
  {
    compte: "614",
    libelle: "ENTRETIEN, RÉPARATION ET MAINTENANCE",
    categorie: "Entretien et maintenance",
    famille: "Pièces et fournitures de maintenance",
    type_bien: "entretien",
    unite_defaut: "pièce",
    items: [
      {
        code: "614.001",
        intitule:
          "Produit d'entretien et maintenance des terrains, plantations, forêts et plans d'eau",
      },
      // Bâtiment bureau
      { code: "614.002", intitule: "Ampoule (pour bureau)" },
      { code: "614.003", intitule: "Applique (pour bureau)" },
      { code: "614.004", intitule: "Arrache clou (pour bureau)" },
      { code: "614.005", intitule: "Baguette (pour bureau)" },
      {
        code: "614.006",
        intitule: "Baies de châssis (remplacement) (pour bureau)",
      },
      { code: "614.007", intitule: "Baignoire complet (pour bureau)" },
      { code: "614.008", intitule: "Bétonnière (pour bureau)" },
      { code: "614.009", intitule: "Bidet simple (pour bureau)" },
      {
        code: "614.010",
        intitule: "Bloc autonome de sécurité (pour bureau)",
      },
      {
        code: "614.011",
        intitule: "Boîte de dérivation de 100 x 100 (pour bureau)",
      },
      {
        code: "614.012",
        intitule: "Boîte étanche de 100 x 100 (pour bureau)",
      },
      { code: "614.013", intitule: "Bouchon pvc (pour bureau)" },
      {
        code: "614.014",
        intitule: "Brasseur d'air (mural, plafonnier) (pour bureau)",
      },
      { code: "614.015", intitule: "Burin (plat, pointu) (pour bureau)" },
      { code: "614.016", intitule: "Câble de terre 29mm2 (pour bureau)" },
      {
        code: "614.017",
        intitule:
          "Câble téléphonique de 06 pairs rouleaux de 100 mètres (pour bureau)",
      },
      { code: "614.018", intitule: "Cadenas de sécurité (pour bureau)" },
      { code: "614.019", intitule: "Carreaux (pour bureau)" },
      { code: "614.020", intitule: "Casque Opus (pour bureau)" },
      {
        code: "614.021",
        intitule: "Chapeau d'aération de pvc (pour bureau)",
      },
      { code: "614.022", intitule: "Chauffe-eau (pour bureau)" },
      { code: "614.023", intitule: "Cheville (pour bureau)" },
      {
        code: "614.024",
        intitule: "Cintreuse des barres d'armature (pour bureau)",
      },
      { code: "614.025", intitule: "Cisaille à béton (pour bureau)" },
      { code: "614.026", intitule: "Clé molette (pour bureau)" },
      { code: "614.027", intitule: "Coffret modulaire (pour bureau)" },
      { code: "614.028", intitule: "Colle forte chaux (pour bureau)" },
      { code: "614.029", intitule: "Collier (pour bureau)" },
      { code: "614.030", intitule: "Contreplaqué (pour bureau)" },
      { code: "614.031", intitule: "Coudes (pour bureau)" },
      { code: "614.032", intitule: "Coupe boulons (pour bureau)" },
      { code: "614.033", intitule: "Coupe carreaux (pour bureau)" },
      { code: "614.034", intitule: "Cuivre nu (pour bureau)" },
      { code: "614.035", intitule: "Cutteur (pour bureau)" },
      { code: "614.036", intitule: "Cylindre simple (pour bureau)" },
      { code: "614.037", intitule: "Déboucheur (pour bureau)" },
      { code: "614.038", intitule: "Décamètre (pour bureau)" },
      { code: "614.039", intitule: "Diluant cellulosique (pour bureau)" },
      { code: "614.040", intitule: "Disque à tronçonner (pour bureau)" },
      {
        code: "614.041",
        intitule:
          "Échelle centaure (coulissante, simple, transformable) (pour bureau)",
      },
      { code: "614.042", intitule: "Embout à chaud (pour bureau)" },
      { code: "614.043", intitule: "Équerre métallique (pour bureau)" },
      {
        code: "614.044",
        intitule: "Escabeau ménager centaure (pour bureau)",
      },
      { code: "614.045", intitule: "Évier (pour bureau)" },
      { code: "614.046", intitule: "Extincteur (pour bureau)" },
      { code: "614.047", intitule: "Fer (pour bureau)" },
      { code: "614.048", intitule: "Fil (téléphonique et TH) (pour bureau)" },
      { code: "614.049", intitule: "Fil de fer barbelé (pour bureau)" },
      {
        code: "614.050",
        intitule: "Flexible de raccordement (pour bureau)",
      },
      { code: "614.051", intitule: "Gant (pour bureau)" },
      { code: "614.052", intitule: "Grillage (pour bureau)" },
      { code: "614.053", intitule: "Interrupteur (pour bureau)" },
      { code: "614.054", intitule: "Isorel (pour bureau)" },
      { code: "614.055", intitule: "Kit douchette (pour bureau)" },
      { code: "614.056", intitule: "Lame de verres (pour bureau)" },
      { code: "614.057", intitule: "Lampe (pour bureau)" },
      { code: "614.058", intitule: "Lubrifiant gébajoint (pour bureau)" },
      { code: "614.059", intitule: "Luminaire plafonnier (pour bureau)" },
      { code: "614.060", intitule: "Mamelon laiton (pour bureau)" },
      { code: "614.061", intitule: "Manche en bois (pour bureau)" },
      { code: "614.062", intitule: "Manchon (pour bureau)" },
      { code: "614.063", intitule: "Marche pied centaure (pour bureau)" },
      {
        code: "614.064",
        intitule: "Marteau de menuiserie (pour bureau)",
      },
      {
        code: "614.065",
        intitule:
          "Mécanisme (à tirette, raccord à poussoir) (pour bureau)",
      },
      { code: "614.066", intitule: "Mèche de forage (pour bureau)" },
      { code: "614.067", intitule: "Mélangeur de lavabo (pour bureau)" },
      { code: "614.068", intitule: "Moquette épaisse (pour bureau)" },
      { code: "614.069", intitule: "Moulure (pour bureau)" },
      { code: "614.070", intitule: "Niveau anti choc (pour bureau)" },
      { code: "614.071", intitule: "Nivotop rectangle (pour bureau)" },
      {
        code: "614.072",
        intitule: "Nivotop trapèze magnétique (pour bureau)",
      },
      { code: "614.073", intitule: "Odomètre (pour bureau)" },
      { code: "614.074", intitule: "Papier abrasif (pour bureau)" },
      { code: "614.075", intitule: "Paumelle (pour bureau)" },
      { code: "614.076", intitule: "Parafoudre (pour bureau)" },
      { code: "614.077", intitule: "Peinture (pour bureau)" },
      { code: "614.078", intitule: "Perceuse à percussion (pour bureau)" },
      {
        code: "614.079",
        intitule: "Perforateur-burineur (pour bureau)",
      },
      { code: "614.080", intitule: "Piquet de terre (pour bureau)" },
      { code: "614.081", intitule: "Pilon compacteur (pour bureau)" },
      {
        code: "614.082",
        intitule:
          "Pince forte électrode, masse, à bec, étaux, molette, multifonction (pour bureau)",
      },
      {
        code: "614.083",
        intitule: "Pistolet (coaxial, peinture) (pour bureau)",
      },
      { code: "614.084", intitule: "Pomme de douche (pour bureau)" },
      { code: "614.085", intitule: "Pompe vide cave (pour bureau)" },
      { code: "614.086", intitule: "Ponceuse excentrique (pour bureau)" },
      { code: "614.087", intitule: "Porte (pour bureau)" },
      {
        code: "614.088",
        intitule: "Porte panneau avec cadre (pour bureau)",
      },
      { code: "614.089", intitule: "Porte rideau (pour bureau)" },
      { code: "614.090", intitule: "Porte-Papier (pour bureau)" },
      {
        code: "614.091",
        intitule: "Porte-Savon/Porte-serviette (pour bureau)",
      },
      { code: "614.092", intitule: "Poupée-Filasse (pour bureau)" },
      {
        code: "614.093",
        intitule: "Prise (antenne et courant) (pour bureau)",
      },
      { code: "614.094", intitule: "Raccord (pour bureau)" },
      { code: "614.095", intitule: "Rallonge (pour bureau)" },
      { code: "614.096", intitule: "Réducteur pvc (pour bureau)" },
      { code: "614.097", intitule: "Réglette (pour bureau)" },
      { code: "614.098", intitule: "Réservoir plastique (pour bureau)" },
      { code: "614.099", intitule: "Robinet (pour bureau)" },
      {
        code: "614.100",
        intitule: "Rondelle poids central du WC (pour bureau)",
      },
      { code: "614.101", intitule: "Scie (pour bureau)" },
      { code: "614.102", intitule: "Serrure (pour bureau)" },
      { code: "614.103", intitule: "Siphon (pour bureau)" },
      { code: "614.104", intitule: "Sonnerie musicale (pour bureau)" },
      { code: "614.105", intitule: "Tablette de lavabo (pour bureau)" },
      {
        code: "614.106",
        intitule: "Té (PVC, pression, Flon) (pour bureau)",
      },
      { code: "614.107", intitule: "Téflon (pour bureau)" },
      { code: "614.108", intitule: "Télérupteur sur rail (pour bureau)" },
      { code: "614.109", intitule: "Tenaille (pour bureau)" },
      {
        code: "614.110",
        intitule: "Tirphons ronds (paquet) (pour bureau)",
      },
      { code: "614.111", intitule: "Tôle (pour bureau)" },
      { code: "614.112", intitule: "Transformateur (pour bureau)" },
      { code: "614.113", intitule: "Tronçonneuse à chaîne (pour bureau)" },
      { code: "614.114", intitule: "Tube orange (pour bureau)" },
      {
        code: "614.115",
        intitule: "Tubes (fluorescents, carré) (pour bureau)",
      },
      { code: "614.116", intitule: "Tuyaux (pour bureau)" },
      { code: "614.117", intitule: "Vanne à boisseau (pour bureau)" },
      {
        code: "614.118",
        intitule: "Vaporisateur pistolet à pression (pour bureau)",
      },
      { code: "614.119", intitule: "Vernis (pour bureau)" },
      { code: "614.120", intitule: "Vis perceuse compacte (pour bureau)" },
      { code: "614.121", intitule: "WC (pour bureau)" },
      // Logement (échantillon représentatif — même liste)
      { code: "614.122", intitule: "Ampoule (pour logement)" },
      { code: "614.123", intitule: "Applique (pour logement)" },
      { code: "614.124", intitule: "Arrache clou (pour logement)" },
      { code: "614.125", intitule: "Baguette (pour logement)" },
      { code: "614.126", intitule: "Baies de châssis (remplacement) (pour logement)" },
      { code: "614.127", intitule: "Baignoire complet (pour logement)" },
      { code: "614.128", intitule: "Bétonnière (pour logement)" },
      { code: "614.129", intitule: "Bidet simple (pour logement)" },
      { code: "614.130", intitule: "Bloc autonome de sécurité (pour logement)" },
      { code: "614.131", intitule: "Boîte de dérivation de 100 x 100 (pour logement)" },
      { code: "614.132", intitule: "Boîte étanche de 100 x 100 (pour logement)" },
      { code: "614.133", intitule: "Bouchon pvc (pour logement)" },
      { code: "614.134", intitule: "Brasseur d'air (mural, plafonnier) (pour logement)" },
      { code: "614.135", intitule: "Burin (plat, pointu) (pour logement)" },
      { code: "614.136", intitule: "Câble de terre 29mm2 (pour logement)" },
      { code: "614.137", intitule: "Câble téléphonique de 06 pairs rouleaux de 100 mètres (pour logement)" },
      { code: "614.138", intitule: "Cadenas de sécurité (pour logement)" },
      { code: "614.139", intitule: "Carreaux (pour logement)" },
      { code: "614.140", intitule: "Casque Opus (pour logement)" },
      { code: "614.141", intitule: "Chauffe-eau (pour logement)" },
      { code: "614.142", intitule: "Cheville (pour logement)" },
      { code: "614.143", intitule: "Cintreuse des barres d'armature (pour logement)" },
      { code: "614.144", intitule: "Cisaille à béton (pour logement)" },
      { code: "614.145", intitule: "Clé molette (pour logement)" },
      { code: "614.146", intitule: "Coffret modulaire (pour logement)" },
      { code: "614.147", intitule: "Colle forte chaux (pour logement)" },
      { code: "614.148", intitule: "Contreplaqué (pour logement)" },
      { code: "614.149", intitule: "Déboucheur (pour logement)" },
      { code: "614.150", intitule: "Peinture (pour logement)" },
      { code: "614.151", intitule: "Robinet (pour logement)" },
      { code: "614.152", intitule: "Serrure (pour logement)" },
      { code: "614.153", intitule: "Tuyaux (pour logement)" },
      { code: "614.154", intitule: "WC (pour logement)" },
      // Usage technique
      { code: "614.155", intitule: "Ampoule (pour usage technique)" },
      { code: "614.156", intitule: "Applique (pour usage technique)" },
      { code: "614.157", intitule: "Baguette (pour usage technique)" },
      { code: "614.158", intitule: "Câble de terre 29mm2 (pour usage technique)" },
      { code: "614.159", intitule: "Cadenas de sécurité (pour usage technique)" },
      { code: "614.160", intitule: "Carreaux (pour usage technique)" },
      { code: "614.161", intitule: "Chauffe-eau (pour usage technique)" },
      { code: "614.162", intitule: "Coffret modulaire (pour usage technique)" },
      { code: "614.163", intitule: "Contreplaqué (pour usage technique)" },
      { code: "614.164", intitule: "Déboucheur (pour usage technique)" },
      { code: "614.165", intitule: "Extincteur (pour usage technique)" },
      { code: "614.166", intitule: "Peinture (pour usage technique)" },
      { code: "614.167", intitule: "Robinet (pour usage technique)" },
      { code: "614.168", intitule: "Serrure (pour usage technique)" },
      { code: "614.169", intitule: "Tuyaux (pour usage technique)" },
      { code: "614.170", intitule: "WC (pour usage technique)" },
      // Nettoyage et hygiène
      { code: "614.171", intitule: "Anneaux pour rideau" },
      { code: "614.172", intitule: "Balai avec manche (coco, en plastique)" },
      {
        code: "614.173",
        intitule: "Balai de cour traditionnel avec manche en bois",
      },
      {
        code: "614.174",
        intitule: "Barre de tringles pour rideau + bouchon et support en fer",
      },
      {
        code: "614.175",
        intitule: "Brosse à laver (à manche, sans manche dur, souple)",
      },
      {
        code: "614.176",
        intitule:
          "Cache-nez avec cartouche de fiche (en forme ronde)",
      },
      { code: "614.177", intitule: "Chamoisine (grand, petit)" },
      { code: "614.178", intitule: "Crésyl" },
      { code: "614.179", intitule: "Déboucheur WC liquide" },
      { code: "614.180", intitule: "Déboucheur WC manuel" },
      { code: "614.181", intitule: "Désodorisant (air life, Arrixaca)" },
      { code: "614.182", intitule: "Désodorisant Ambi pur" },
      { code: "614.183", intitule: "Désodorisant Essence de citronnelle" },
      {
        code: "614.184",
        intitule: "Désodorisant WC (HARPIC, NETTO ou APTA)",
      },
      { code: "614.185", intitule: "Désodorisant WC liquide" },
      { code: "614.186", intitule: "Éponge double face" },
      { code: "614.187", intitule: "Éponge végétale" },
      { code: "614.188", intitule: "Essuie vitre (Bingo et autres)" },
      { code: "614.189", intitule: "Gel à main (hydro alcoolique, etc.)" },
      { code: "614.190", intitule: "Insecticide" },
      { code: "614.191", intitule: "Javel" },
      { code: "614.192", intitule: "Javel CLEAN (1 litre, 350ml)" },
      { code: "614.193", intitule: "Nettoyant bi-javellisant" },
      { code: "614.194", intitule: "Paire de gants de ménage" },
      { code: "614.195", intitule: "Paire de gants protection chimique" },
      { code: "614.196", intitule: "Panier à ordures pour hôpitaux" },
      { code: "614.197", intitule: "Papier hygiénique" },
      { code: "614.198", intitule: "Papier mouchoir" },
      { code: "614.199", intitule: "Pèle plastique" },
      { code: "614.200", intitule: "Raclette carreaux et sols" },
      { code: "614.201", intitule: "Rouleau (de 2 compacts; de 3 blancs; de 3 décoré etc.)" },
      { code: "614.202", intitule: "Savon" },
      { code: "614.203", intitule: "Savon détergent" },
      { code: "614.204", intitule: "Seau" },
      { code: "614.205", intitule: "Serpillère" },
      { code: "614.206", intitule: "Serviette" },
      { code: "614.207", intitule: "Torchon de bureau" },
      // Entretien mobilier et véhicules
      {
        code: "614.208",
        intitule: "Entretien et maintenance du mobilier et matériel de bureau",
      },
      {
        code: "614.209",
        intitule: "Entretien et maintenance du mobilier et matériel de logement",
      },
      // Pièces détachées véhicules (sélection principale)
      { code: "614.210", intitule: "Actionneur volet" },
      { code: "614.211", intitule: "Additif carburant (essence, gaz oil)" },
      { code: "614.212", intitule: "Alternateur" },
      { code: "614.213", intitule: "Amortisseurs (arrière, avant droit, avant gauche)" },
      { code: "614.214", intitule: "Antenne radio" },
      { code: "614.215", intitule: "Batteries" },
      { code: "614.216", intitule: "Bougies (d'allumage, de préchauffage, etc.)" },
      { code: "614.217", intitule: "Câbles (compteur, de frein, d'embrayage, etc.)" },
      { code: "614.218", intitule: "Courroies (kit, alternateur, clim, distribution, etc.)" },
      { code: "614.219", intitule: "Démarreur" },
      { code: "614.220", intitule: "Demi-arbre de transmission" },
      { code: "614.221", intitule: "Disques (de frein, d'embrayage)" },
      { code: "614.222", intitule: "Durite (supérieure, inférieure, radiateur)" },
      { code: "614.223", intitule: "Filtres (à air, à gasoil, à essence, à huile, à pollen, etc.)" },
      { code: "614.224", intitule: "Fusible" },
      { code: "614.225", intitule: "Garnitures (de frein, colt, arrière)" },
      { code: "614.226", intitule: "Huile (de direction, à boîte, à moteur, à pont, compresseur)" },
      { code: "614.227", intitule: "Injecteur complet" },
      { code: "614.228", intitule: "Jantes" },
      { code: "614.229", intitule: "Joints (vidange, cache culbuteur, carter, etc.)" },
      { code: "614.230", intitule: "Kit (d'embrayage, de distribution, de disque frein, etc.)" },
      { code: "614.231", intitule: "Liquides (de frein, de lave glace, de refroidissement, etc.)" },
      { code: "614.232", intitule: "Maître-cylindre (de frein, d'embrayage)" },
      { code: "614.233", intitule: "Pneu" },
      { code: "614.234", intitule: "Plaquettes de frein (avant, arrière, kit)" },
      { code: "614.235", intitule: "Pompes (à eau, à huile, à carburant, etc.)" },
      { code: "614.236", intitule: "Radiateur" },
      { code: "614.237", intitule: "Rotule (de direction, de suspension, etc.)" },
      { code: "614.238", intitule: "Roulements" },
      { code: "614.239", intitule: "Segment" },
      { code: "614.240", intitule: "Silent bloc" },
      { code: "614.241", intitule: "Soufflet (cardan, crémaillère, amortisseur, etc.)" },
      { code: "614.242", intitule: "Supports (moteur, boîte vitesse, radiateur, etc.)" },
      { code: "614.243", intitule: "Thermostat" },
      { code: "614.244", intitule: "Transmission" },
      { code: "614.245", intitule: "Turbo" },
      { code: "614.246", intitule: "Tuyaux (de frein, d'alimentation carburant, d'eau, etc.)" },
      { code: "614.247", intitule: "Vilebrequin" },
      { code: "614.248", intitule: "Vitres (custode, de porte)" },
      { code: "614.249", intitule: "Volant moteur" },
      {
        code: "614.250",
        intitule: "Entretien et maintenance des ouvrages et infrastructures",
      },
      {
        code: "614.251",
        intitule: "Entretien et maintenance des réseaux informatiques",
      },
      {
        code: "614.252",
        intitule:
          "Entretien et maintenance du matériel et outillages techniques",
      },
      {
        code: "614.253",
        intitule:
          "Entretien et maintenance des avions, navires et autres véhicules spéciaux",
      },
      { code: "614.254", intitule: "Autres entretiens et maintenances" },
    ],
  },
];

// Statistiques utiles
export const STATS_PARTIE_B = {
  total_groupes: PARTIE_B_STOCK.length,
  total_items: PARTIE_B_STOCK.reduce((acc, g) => acc + g.items.length, 0),
  comptes: PARTIE_B_STOCK.map((g) => g.compte),
};
