/**
 * PARTIE A — IMMOBILISATIONS (Codes 2xx)
 * Source : ANNEXE_NOMACT_SIGNE.PDF
 * Type : Biens durables → suivi INDIVIDUEL avec identifiant unique
 * Usage : Module Immobilisations uniquement
 */

export interface NomenclatureItem {
  code: string;
  intitule: string;
}

export interface NomenclatureGroupe {
  compte: string;
  libelle: string;
  categorie: string;
  famille: string;
  type_bien: "immobilisation";
  items: NomenclatureItem[];
}

export const PARTIE_A_IMMOBILISATIONS: NomenclatureGroupe[] = [
  // ─────────────────────────────────────────────────────────────────────────
  // IMMOBILISATIONS INCORPORELLES (20x)
  // ─────────────────────────────────────────────────────────────────────────
  {
    compte: "201",
    libelle: "FRAIS D'ÉTABLISSEMENT",
    categorie: "Immobilisations incorporelles",
    famille: "Frais d'établissement",
    type_bien: "immobilisation",
    items: [
      { code: "201.001", intitule: "Frais d'établissement" },
      { code: "201.999", intitule: "Autres frais d'établissement" },
    ],
  },
  {
    compte: "202",
    libelle: "PRIME DE REMBOURSEMENT D'OBLIGATION",
    categorie: "Immobilisations incorporelles",
    famille: "Obligations",
    type_bien: "immobilisation",
    items: [
      { code: "202.001", intitule: "Primes de remboursement des obligations" },
      {
        code: "202.999",
        intitule: "Autres primes de remboursement d'obligations",
      },
    ],
  },
  {
    compte: "211",
    libelle: "FRAIS DE RECHERCHE ET DE DÉVELOPPEMENT",
    categorie: "Immobilisations incorporelles",
    famille: "Recherche & Développement",
    type_bien: "immobilisation",
    items: [
      {
        code: "211.001",
        intitule: "Installation de nouvelles technologies",
      },
      {
        code: "211.002",
        intitule:
          "Recherches en vue de la valorisation des ressources humaines",
      },
      { code: "211.003", intitule: "Frais d'études techniques immobilisés" },
      {
        code: "211.004",
        intitule: "Recherches scientifiques et développement",
      },
      {
        code: "211.999",
        intitule: "Autres frais de recherche et de développement",
      },
    ],
  },
  {
    compte: "212",
    libelle: "BREVETS, LICENCES, CONCESSIONS ET DROITS",
    categorie: "Immobilisations incorporelles",
    famille: "Droits de propriété intellectuelle",
    type_bien: "immobilisation",
    items: [
      { code: "212.001", intitule: "Brevets" },
      { code: "212.002", intitule: "Licences" },
      { code: "212.003", intitule: "Concessions" },
      { code: "212.004", intitule: "Droits" },
      {
        code: "212.999",
        intitule: "Autres brevets, licences, concessions et droits",
      },
    ],
  },
  {
    compte: "213",
    libelle: "LOGICIELS",
    categorie: "Immobilisations incorporelles",
    famille: "Logiciels et systèmes informatiques",
    type_bien: "immobilisation",
    items: [
      {
        code: "213.001",
        intitule: "Développement de systèmes d'exploitation",
      },
      {
        code: "213.002",
        intitule:
          "Acquisition et développement du logiciel de gestion financière et comptable des collectivités territoriales",
      },
      {
        code: "213.003",
        intitule:
          "Acquisition et développement du logiciel de la comptabilité des matières",
      },
      { code: "213.004", intitule: "Droit d'exploitation de logiciel" },
      { code: "213.999", intitule: "Autres logiciels" },
    ],
  },
  {
    compte: "214",
    libelle: "MARQUES",
    categorie: "Immobilisations incorporelles",
    famille: "Marques et identité",
    type_bien: "immobilisation",
    items: [
      { code: "214.001", intitule: "Marques" },
      { code: "214.999", intitule: "Autres marques" },
    ],
  },
  {
    compte: "215",
    libelle: "DROIT AU BAIL",
    categorie: "Immobilisations incorporelles",
    famille: "Droits immobiliers",
    type_bien: "immobilisation",
    items: [
      { code: "215.001", intitule: "Droit au bail" },
      { code: "215.999", intitule: "Autres droit au bail" },
    ],
  },
  {
    compte: "219",
    libelle: "AUTRES DROITS ET VALEURS INCORPORELS",
    categorie: "Immobilisations incorporelles",
    famille: "Autres incorporels",
    type_bien: "immobilisation",
    items: [
      {
        code: "219.999",
        intitule: "Autres droits et valeurs incorporelles non ventilés ailleurs",
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // TERRAINS & SOLS (22x)
  // ─────────────────────────────────────────────────────────────────────────
  {
    compte: "221",
    libelle: "TERRAINS",
    categorie: "Terrains et sols",
    famille: "Terrains",
    type_bien: "immobilisation",
    items: [
      { code: "221.001", intitule: "Terrain à bâtir" },
      { code: "221.002", intitule: "Terrain d'exploitation agricole" },
      {
        code: "221.003",
        intitule: "Terrain pour bâtiments administratifs à usage de bureau",
      },
      {
        code: "221.004",
        intitule: "Terrain pour bâtiments administratifs à usage de logement",
      },
      {
        code: "221.005",
        intitule: "Terrain pour bâtiments administratifs à usage technique",
      },
      { code: "221.006", intitule: "Terrain pour réserves administratives" },
      { code: "221.999", intitule: "Autres terrains" },
    ],
  },
  {
    compte: "222",
    libelle: "SOUS-SOLS, GISEMENTS ET CARRIÈRES",
    categorie: "Terrains et sols",
    famille: "Sous-sols et ressources naturelles",
    type_bien: "immobilisation",
    items: [
      { code: "222.001", intitule: "Carrières" },
      { code: "222.002", intitule: "Gisements miniers" },
      { code: "222.003", intitule: "Gisements d'hydrocarbures" },
      {
        code: "222.999",
        intitule: "Autres sous-sols, gisements et carrières",
      },
    ],
  },
  {
    compte: "223",
    libelle: "PLANTATIONS ET FORÊTS",
    categorie: "Terrains et sols",
    famille: "Agriculture et forêts",
    type_bien: "immobilisation",
    items: [
      { code: "223.001", intitule: "Plantation de café" },
      { code: "223.002", intitule: "Plantation de cacao" },
      { code: "223.003", intitule: "Plantation d'anacardes" },
      { code: "223.004", intitule: "Forêts" },
      { code: "223.005", intitule: "Plants-forêts" },
      { code: "223.999", intitule: "Autres plantations et forêts" },
    ],
  },
  {
    compte: "224",
    libelle: "PLANS D'EAU",
    categorie: "Terrains et sols",
    famille: "Ressources hydrauliques",
    type_bien: "immobilisation",
    items: [
      { code: "224.001", intitule: "Périmètre irrigué" },
      { code: "224.002", intitule: "Forage" },
      { code: "224.003", intitule: "Aménagement hydro-agricole" },
      { code: "224.999", intitule: "Autres plans d'eau" },
    ],
  },
  {
    compte: "225",
    libelle: "AMÉNAGEMENT DE TERRAINS",
    categorie: "Terrains et sols",
    famille: "Aménagements fonciers",
    type_bien: "immobilisation",
    items: [
      { code: "225.001", intitule: "Aménagements des terrains" },
      { code: "225.999", intitule: "Autres aménagements des terrains" },
    ],
  },
  {
    compte: "226",
    libelle: "AMÉNAGEMENT DES SOUS-SOLS",
    categorie: "Terrains et sols",
    famille: "Aménagements fonciers",
    type_bien: "immobilisation",
    items: [
      { code: "226.001", intitule: "Aménagements de sous-sols" },
      { code: "226.999", intitule: "Autres aménagements de sous-sols" },
    ],
  },
  {
    compte: "227",
    libelle: "TERRAINS MIS EN CONCESSION",
    categorie: "Terrains et sols",
    famille: "Concessions foncières",
    type_bien: "immobilisation",
    items: [
      { code: "227.001", intitule: "Terrains mis en concession" },
      { code: "227.999", intitule: "Autres terrains mis en concession" },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // BÂTIMENTS (23x)
  // ─────────────────────────────────────────────────────────────────────────
  {
    compte: "231",
    libelle: "BÂTIMENTS ADMINISTRATIFS À USAGE DE BUREAU",
    categorie: "Bâtiments administratifs",
    famille: "Bureaux",
    type_bien: "immobilisation",
    items: [
      {
        code: "231.001",
        intitule: "Acquisition d'immeuble à étage pour usage de bureau",
      },
      {
        code: "231.002",
        intitule: "Construction d'immeuble à étage pour usage de bureau",
      },
      {
        code: "231.003",
        intitule:
          "Grosse réparation des bâtiments administratifs à usage de bureau",
      },
      { code: "231.004", intitule: "Local pour archives" },
      {
        code: "231.005",
        intitule: "Acquisition de villa administrative à usage de bureau",
      },
      {
        code: "231.006",
        intitule: "Construction de villa administrative à usage de bureau",
      },
      {
        code: "231.999",
        intitule: "Autres bâtiments administratifs à usage de bureau",
      },
    ],
  },
  {
    compte: "232",
    libelle: "BÂTIMENTS ADMINISTRATIFS À USAGE DE LOGEMENT",
    categorie: "Bâtiments administratifs",
    famille: "Logements",
    type_bien: "immobilisation",
    items: [
      {
        code: "232.001",
        intitule: "Acquisition d'immeuble à étage pour usage de logement",
      },
      {
        code: "232.002",
        intitule: "Construction d'immeuble à étage pour usage de logement",
      },
      { code: "232.003", intitule: "Dépendance" },
      {
        code: "232.004",
        intitule: "Grosse réparation des bâtiments à usage de logement",
      },
      {
        code: "232.005",
        intitule: "Acquisition de villa administrative à usage de logement",
      },
      {
        code: "232.006",
        intitule: "Construction de villa administrative à usage de logement",
      },
      {
        code: "232.999",
        intitule: "Autres bâtiments administratifs à usage de logement",
      },
    ],
  },
  {
    compte: "233",
    libelle: "BÂTIMENTS ADMINISTRATIFS À USAGE TECHNIQUE",
    categorie: "Bâtiments administratifs",
    famille: "Bâtiments techniques",
    type_bien: "immobilisation",
    items: [
      { code: "233.001", intitule: "Atelier" },
      { code: "233.002", intitule: "Bâtiment de laboratoire" },
      { code: "233.003", intitule: "Bâtiment des soins de santé" },
      { code: "233.004", intitule: "Bâtiment pédagogique" },
      {
        code: "233.005",
        intitule: "Acquisition de bâtiments à usage agricole",
      },
      {
        code: "233.006",
        intitule: "Construction de bâtiments à usage agricole",
      },
      {
        code: "233.007",
        intitule: "Aménagement de bâtiments à usage agricole",
      },
      { code: "233.008", intitule: "Clôture" },
      {
        code: "233.009",
        intitule: "Grosse réparation des bâtiments à usage technique",
      },
      { code: "233.010", intitule: "Hangar" },
      { code: "233.011", intitule: "Guérite" },
      {
        code: "233.012",
        intitule: "Immeuble à niveaux à usage technique",
      },
      { code: "233.013", intitule: "Local pour vigile" },
      { code: "233.014", intitule: "Local de groupe électrogène" },
      { code: "233.015", intitule: "Magasin" },
      { code: "233.016", intitule: "Parking" },
      { code: "233.017", intitule: "Réfectoire" },
      { code: "233.018", intitule: "Toilette externe" },
      {
        code: "233.019",
        intitule: "Acquisition de villas à usage technique",
      },
      {
        code: "233.020",
        intitule: "Construction de villas à usage technique",
      },
      {
        code: "233.999",
        intitule: "Autres bâtiments administratifs à usage technique",
      },
    ],
  },
  {
    compte: "234",
    libelle: "OUVRAGES",
    categorie: "Ouvrages et infrastructures",
    famille: "Ouvrages d'art",
    type_bien: "immobilisation",
    items: [
      { code: "234.001", intitule: "Aéroport" },
      { code: "234.002", intitule: "Aérodrome" },
      { code: "234.003", intitule: "Aire de repos" },
      { code: "234.004", intitule: "Barrage" },
      { code: "234.005", intitule: "Base aérienne" },
      { code: "234.006", intitule: "Bassin" },
      { code: "234.007", intitule: "Châteaux d'eau" },
      { code: "234.008", intitule: "Chemin de fer" },
      { code: "234.009", intitule: "Citerne d'eau (en bois, en fer, etc.)" },
      { code: "234.010", intitule: "Digue" },
      { code: "234.011", intitule: "Embarcadère" },
      { code: "234.012", intitule: "Échangeur" },
      { code: "234.013", intitule: "Incinérateur" },
      { code: "234.014", intitule: "Monument" },
      { code: "234.015", intitule: "Parc de vaccination (animaux)" },
      { code: "234.016", intitule: "Pont" },
      { code: "234.017", intitule: "Port" },
      { code: "234.018", intitule: "Poste de dépotage" },
      { code: "234.019", intitule: "Poste de péage" },
      { code: "234.020", intitule: "Rond-point" },
      {
        code: "234.021",
        intitule: "Silos de stockage de céréales et autres produits",
      },
      { code: "234.022", intitule: "Soute" },
      { code: "234.999", intitule: "Autres ouvrages" },
    ],
  },
  {
    compte: "235",
    libelle: "INFRASTRUCTURES",
    categorie: "Ouvrages et infrastructures",
    famille: "Infrastructures publiques",
    type_bien: "immobilisation",
    items: [
      { code: "235.001", intitule: "Route bitumée" },
      { code: "235.002", intitule: "Piste" },
      { code: "235.003", intitule: "Adduction d'eau potable" },
      { code: "235.004", intitule: "Réseaux téléphoniques et médias" },
      { code: "235.005", intitule: "Réseaux d'assainissement" },
      { code: "235.006", intitule: "Marché" },
      { code: "235.007", intitule: "Gare routière" },
      { code: "235.008", intitule: "Gare ferroviaire" },
      { code: "235.009", intitule: "Centre cultuel" },
      { code: "235.010", intitule: "Centre artisanal" },
      { code: "235.011", intitule: "Stade" },
      { code: "235.012", intitule: "Terrain ou plateau de sport" },
      { code: "235.013", intitule: "Piscine communale" },
      { code: "235.014", intitule: "Centre de loisirs" },
      { code: "235.999", intitule: "Autres infrastructures" },
    ],
  },
  {
    compte: "236",
    libelle: "RÉSEAUX INFORMATIQUES",
    categorie: "Ouvrages et infrastructures",
    famille: "Réseaux numériques",
    type_bien: "immobilisation",
    items: [
      {
        code: "236.001",
        intitule:
          "Réseau du système d'information de la gestion financière et comptable des collectivités territoriales",
      },
      {
        code: "236.002",
        intitule:
          "Réseau du système d'information de la comptabilité des matières",
      },
      { code: "236.999", intitule: "Autres réseaux informatiques" },
    ],
  },
  {
    compte: "237",
    libelle: "RÉSEAUX D'ÉLECTRIFICATION",
    categorie: "Ouvrages et infrastructures",
    famille: "Réseaux électriques",
    type_bien: "immobilisation",
    items: [
      { code: "237.001", intitule: "Réseau électrique" },
      { code: "237.999", intitule: "Autres réseaux d'électrification" },
    ],
  },
  {
    compte: "239",
    libelle:
      "AUTRES ACQUISITIONS, CONSTRUCTIONS ET GROSSES RÉPARATIONS D'IMMEUBLES",
    categorie: "Ouvrages et infrastructures",
    famille: "Autres immeubles",
    type_bien: "immobilisation",
    items: [
      {
        code: "239.999",
        intitule:
          "Autres acquisitions, constructions et grosses réparations d'immeubles",
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // MOBILIER & MATÉRIEL (24x)
  // ─────────────────────────────────────────────────────────────────────────
  {
    compte: "241",
    libelle: "MOBILIER ET MATÉRIEL DE BUREAU ET DE LOGEMENT",
    categorie: "Mobilier et équipements",
    famille: "Mobilier de bureau",
    type_bien: "immobilisation",
    items: [
      { code: "241.001", intitule: "Agrafeuse géante" },
      { code: "241.002", intitule: "Antenne parabolique et décodeur" },
      { code: "241.003", intitule: "Aquarium de bureau et de logement" },
      { code: "241.004", intitule: "Armoire" },
      { code: "241.005", intitule: "Aspirateur" },
      { code: "241.006", intitule: "Bac à fiches" },
      { code: "241.007", intitule: "Banc" },
      { code: "241.008", intitule: "Bibliothèque" },
      { code: "241.009", intitule: "Bouteille de gaz" },
      { code: "241.010", intitule: "Buffet" },
      { code: "241.011", intitule: "Bureau" },
      { code: "241.012", intitule: "Cafetière multifonction" },
      { code: "241.013", intitule: "Caisson" },
      { code: "241.014", intitule: "Canapé ou Sofa" },
      { code: "241.015", intitule: "Cantine métallique" },
      { code: "241.016", intitule: "Chaise" },
      { code: "241.017", intitule: "Chariot de transport" },
      { code: "241.018", intitule: "Chauffe-eau" },
      { code: "241.019", intitule: "Chevalet de conférence" },
      { code: "241.020", intitule: "Classeur" },
      { code: "241.021", intitule: "Climatiseur" },
      { code: "241.022", intitule: "Coffre-fort" },
      { code: "241.023", intitule: "Coffret" },
      {
        code: "241.024",
        intitule: "Compteur, détecteur de faux billets/monnaie",
      },
      { code: "241.025", intitule: "Comptoir" },
      { code: "241.026", intitule: "Congélateur" },
      { code: "241.027", intitule: "Cuisinière (multifonction)" },
      { code: "241.028", intitule: "Réchaud" },
      { code: "241.029", intitule: "Four" },
      { code: "241.030", intitule: "Micro-onde" },
      { code: "241.031", intitule: "Destructeur de document" },
      { code: "241.032", intitule: "Distributeur/fontaine d'eau" },
      { code: "241.033", intitule: "Divan" },
      { code: "241.034", intitule: "Échelle" },
      { code: "241.035", intitule: "Écran de projection" },
      { code: "241.036", intitule: "Éditeur de papier" },
      { code: "241.037", intitule: "Étagère des archives" },
      { code: "241.038", intitule: "Extincteur" },
      { code: "241.039", intitule: "Fauteuil de salon complet" },
      { code: "241.040", intitule: "Fauteuil de salon individuel" },
      { code: "241.041", intitule: "Fauteuil directeur" },
      { code: "241.042", intitule: "Fer à repasser" },
      { code: "241.043", intitule: "Guéridon" },
      { code: "241.044", intitule: "Humidificateur" },
      { code: "241.045", intitule: "Lampe de bureau" },
      { code: "241.046", intitule: "Lave main" },
      { code: "241.047", intitule: "Lit" },
      { code: "241.048", intitule: "Lit camping" },
      { code: "241.049", intitule: "Machine à calculer" },
      { code: "241.050", intitule: "Machine à écrire" },
      { code: "241.051", intitule: "Machine à relier" },
      { code: "241.052", intitule: "Machine offset" },
      { code: "241.053", intitule: "Magnétophone" },
      { code: "241.054", intitule: "Malette" },
      { code: "241.055", intitule: "Massicot" },
      { code: "241.056", intitule: "Matelas" },
      { code: "241.057", intitule: "Meuble télé" },
      { code: "241.058", intitule: "Panneau enseigne" },
      { code: "241.059", intitule: "Panneau publicitaire" },
      { code: "241.060", intitule: "Perforeuse géante" },
      { code: "241.061", intitule: "Porte manteau" },
      { code: "241.062", intitule: "Poste radio" },
      { code: "241.063", intitule: "Poste téléviseur" },
      { code: "241.064", intitule: "Pupitre" },
      { code: "241.065", intitule: "Réfrigérateur" },
      { code: "241.066", intitule: "Régulateur de tension" },
      { code: "241.067", intitule: "Ronéotyper" },
      { code: "241.068", intitule: "Sirène" },
      { code: "241.069", intitule: "Table à manger" },
      { code: "241.070", intitule: "Table d'ordinateur" },
      { code: "241.071", intitule: "Table de réunion" },
      { code: "241.072", intitule: "Tableau d'affichage" },
      { code: "241.073", intitule: "Tabouret" },
      { code: "241.074", intitule: "Téléphone, fax, télex" },
      { code: "241.075", intitule: "Thermos" },
      { code: "241.076", intitule: "Trépieds" },
      { code: "241.077", intitule: "Urne" },
      { code: "241.078", intitule: "Ventilateur sur pieds" },
      { code: "241.079", intitule: "Vidéo projecteur" },
      {
        code: "241.999",
        intitule: "Autres mobiliers et matériels de bureau et de logement",
      },
    ],
  },
  {
    compte: "242",
    libelle: "MATÉRIELS INFORMATIQUES DE BUREAU",
    categorie: "Mobilier et équipements",
    famille: "Informatique",
    type_bien: "immobilisation",
    items: [
      { code: "242.001", intitule: "Ordinateur de bureau" },
      { code: "242.002", intitule: "Imprimante" },
      { code: "242.003", intitule: "Ordinateur portable" },
      { code: "242.004", intitule: "Onduleur" },
      { code: "242.005", intitule: "Serveurs de réseau" },
      { code: "242.006", intitule: "Tablette" },
      { code: "242.007", intitule: "Switch" },
      { code: "242.008", intitule: "Disque dur externe" },
      { code: "242.009", intitule: "Armoire informatique" },
      { code: "242.010", intitule: "Coffret informatique" },
      { code: "242.011", intitule: "Photocopieuse" },
      { code: "242.012", intitule: "Scanner" },
      { code: "242.013", intitule: "Étiqueteuse" },
      { code: "242.014", intitule: "Terminal PMU" },
      { code: "242.015", intitule: "Routeur" },
      { code: "242.016", intitule: "Éditeur de chèques" },
      { code: "242.017", intitule: "Modem (clé de connexion...)" },
      { code: "242.018", intitule: "Caméra" },
      { code: "242.019", intitule: "Appareil photo" },
      { code: "242.020", intitule: "Répéteur" },
      { code: "242.999", intitule: "Autres matériels informatiques" },
    ],
  },
  {
    compte: "243",
    libelle: "MATÉRIEL DE TRANSPORT DE SERVICE ET DE FONCTION",
    categorie: "Mobilier et équipements",
    famille: "Transport individuel",
    type_bien: "immobilisation",
    items: [
      { code: "243.001", intitule: "Moto" },
      { code: "243.002", intitule: "Voiture" },
      { code: "243.003", intitule: "Vélo" },
      {
        code: "243.999",
        intitule: "Autres matériels de transport de service et de fonction",
      },
    ],
  },
  {
    compte: "244",
    libelle: "MATÉRIELS ET OUTILLAGES TECHNIQUES",
    categorie: "Mobilier et équipements",
    famille: "Outillage technique",
    type_bien: "immobilisation",
    items: [
      { code: "244.001", intitule: "Cage à grimper (jardin d'enfants)" },
      { code: "244.002", intitule: "Chargeur de batterie" },
      { code: "244.003", intitule: "Concasseur-broyeur" },
      { code: "244.004", intitule: "Étau d'établi" },
      { code: "244.005", intitule: "Groupe électrogène" },
      { code: "244.006", intitule: "Lampe de mineur" },
      { code: "244.007", intitule: "Machine d'extraction" },
      { code: "244.008", intitule: "Meuleuse d'angle" },
      { code: "244.009", intitule: "Moule de fabrique de savon" },
      { code: "244.010", intitule: "Moulin" },
      { code: "244.011", intitule: "Plaque solaire" },
      { code: "244.012", intitule: "Poste à souder" },
      { code: "244.013", intitule: "Rabot (mine)" },
      { code: "244.014", intitule: "Tréteau" },
      { code: "244.015", intitule: "Trousse de cuvelage" },
      { code: "244.016", intitule: "Usine de décorticage" },
      { code: "244.017", intitule: "Abreuvoir" },
      { code: "244.018", intitule: "Affûteuse" },
      { code: "244.019", intitule: "Agitateur" },
      { code: "244.020", intitule: "Agrafeuse gros travaux" },
      { code: "244.021", intitule: "Ampèremètre" },
      { code: "244.022", intitule: "Appareil à étanchéité" },
      { code: "244.023", intitule: "Appareil de centre de gravité" },
      { code: "244.024", intitule: "Appareil de récupération" },
      { code: "244.025", intitule: "Appareil de test réfrigérant" },
      { code: "244.026", intitule: "Appareil pour interférence mécanique" },
      { code: "244.027", intitule: "Appareil respiratoire" },
      { code: "244.028", intitule: "Armoire à bac" },
      { code: "244.029", intitule: "Armoire de rangement" },
      { code: "244.030", intitule: "Armoire métallique" },
      { code: "244.031", intitule: "Autel" },
      { code: "244.032", intitule: "Baie" },
      { code: "244.033", intitule: "Balance" },
      { code: "244.034", intitule: "Balance de labo" },
      { code: "244.035", intitule: "Balançoires (jardin d'enfants)" },
      { code: "244.036", intitule: "Ballon" },
      { code: "244.037", intitule: "Banc de redressage" },
      { code: "244.038", intitule: "Banc didactique" },
      { code: "244.039", intitule: "Bassine en aluminium" },
      { code: "244.040", intitule: "Bassine en plastique" },
      { code: "244.041", intitule: "Boudineuse" },
      { code: "244.042", intitule: "Burin" },
      { code: "244.043", intitule: "Calculatrice" },
      { code: "244.044", intitule: "Calorimètre" },
      { code: "244.045", intitule: "Carte graphique" },
      { code: "244.046", intitule: "Cheval mobile (jardin d'enfants)" },
      { code: "244.047", intitule: "Cintreuse hydraulique" },
      { code: "244.048", intitule: "Cisaille" },
      { code: "244.049", intitule: "Compresseur" },
      { code: "244.050", intitule: "Corde pour le grimpé" },
      { code: "244.051", intitule: "Cordeau en nylon" },
      { code: "244.052", intitule: "Coupe papier" },
      { code: "244.053", intitule: "Couteau" },
      { code: "244.054", intitule: "Cric" },
      { code: "244.055", intitule: "Cuillère" },
      { code: "244.056", intitule: "Daba" },
      { code: "244.057", intitule: "Décamètre" },
      { code: "244.058", intitule: "Décrasseuse manuel" },
      { code: "244.059", intitule: "Dégauchisseuse" },
      { code: "244.060", intitule: "Démonte pneu" },
      { code: "244.061", intitule: "Démonte ressort" },
      { code: "244.062", intitule: "Dynamomètre" },
      { code: "244.063", intitule: "Échotiers de science" },
      { code: "244.064", intitule: "Électroscope trépieds" },
      { code: "244.065", intitule: "Élévateur mobile" },
      { code: "244.066", intitule: "Enclume" },
      { code: "244.067", intitule: "Équerre" },
      { code: "244.068", intitule: "Équilibreuse de roues" },
      { code: "244.069", intitule: "Escabeau" },
      { code: "244.070", intitule: "Établi de travail" },
      { code: "244.071", intitule: "Étau" },
      { code: "244.072", intitule: "Étuve" },
      { code: "244.073", intitule: "Évaporateur" },
      { code: "244.074", intitule: "Filière électrique" },
      { code: "244.075", intitule: "Forge" },
      { code: "244.076", intitule: "Fouet" },
      { code: "244.077", intitule: "Four électrique" },
      { code: "244.078", intitule: "Fourchette" },
      { code: "244.079", intitule: "Fraiseuse" },
      { code: "244.080", intitule: "Gan" },
      { code: "244.081", intitule: "Générateurs rhéostat" },
      { code: "244.082", intitule: "Griffe" },
      { code: "244.083", intitule: "Grue girafe" },
      { code: "244.084", intitule: "Houe" },
      { code: "244.085", intitule: "Lampe haploïde" },
      { code: "244.086", intitule: "Louche" },
      { code: "244.087", intitule: "Loupe" },
      { code: "244.088", intitule: "Machine à relier" },
      { code: "244.089", intitule: "Machine à reliure" },
      { code: "244.090", intitule: "Machine à sertir" },
      { code: "244.091", intitule: "Machine de wimshurst" },
      { code: "244.092", intitule: "Maquette injection" },
      { code: "244.093", intitule: "Marbre de contrôle" },
      { code: "244.094", intitule: "Masse" },
      { code: "244.095", intitule: "Massette" },
      { code: "244.096", intitule: "Mesureur de terre" },
      { code: "244.097", intitule: "Micro-ampèremètre" },
      { code: "244.098", intitule: "Modèles moléculaires" },
      { code: "244.099", intitule: "Montre de bureau" },
      { code: "244.100", intitule: "Mortaiseuse" },
      { code: "244.101", intitule: "Moteur à cage" },
      { code: "244.102", intitule: "Moteur à quatre temps mécanique" },
      { code: "244.103", intitule: "Moteur asynchrone" },
      { code: "244.104", intitule: "Moteur didactique" },
      { code: "244.105", intitule: "Moteur injection" },
      { code: "244.106", intitule: "Moteur monophasé" },
      { code: "244.107", intitule: "Moteur triphasé" },
      { code: "244.108", intitule: "Motopompe" },
      { code: "244.109", intitule: "Moule" },
      { code: "244.110", intitule: "Mouleuse" },
      { code: "244.111", intitule: "Multimètre" },
      { code: "244.112", intitule: "Myographe" },
      { code: "244.113", intitule: "Oscilloscope" },
      { code: "244.114", intitule: "Paire de bottes" },
      { code: "244.115", intitule: "Palan" },
      { code: "244.116", intitule: "Panneau de grave sauder" },
      { code: "244.117", intitule: "Pelle" },
      { code: "244.118", intitule: "Perceuse" },
      { code: "244.119", intitule: "Petit tour" },
      { code: "244.120", intitule: "Pieds de machine" },
      { code: "244.121", intitule: "Pioche" },
      { code: "244.122", intitule: "Plan incliné" },
      { code: "244.123", intitule: "Plat" },
      { code: "244.124", intitule: "Plieuse" },
      { code: "244.125", intitule: "Poêle" },
      { code: "244.126", intitule: "Poids" },
      { code: "244.127", intitule: "Pompe" },
      { code: "244.128", intitule: "Ponceuse" },
      { code: "244.129", intitule: "Pont élévateur (fixe et mobile)" },
      { code: "244.130", intitule: "Poste à arc" },
      { code: "244.131", intitule: "Poste à souder" },
      { code: "244.132", intitule: "Pousse-pousse (jardin d'enfants)" },
      { code: "244.133", intitule: "Presse hydraulique" },
      { code: "244.134", intitule: "Prisme" },
      { code: "244.135", intitule: "Projecteur de labo" },
      { code: "244.136", intitule: "Pulvérisateur" },
      { code: "244.137", intitule: "Pyromètre décadrant" },
      { code: "244.138", intitule: "Raboteuse" },
      { code: "244.139", intitule: "Raglan" },
      { code: "244.140", intitule: "Râteau" },
      { code: "244.141", intitule: "Rectifieuse" },
      { code: "244.142", intitule: "Refroidisseur d'eau" },
      { code: "244.143", intitule: "Règle métallique" },
      { code: "244.144", intitule: "Régulateur de tension" },
      { code: "244.145", intitule: "Risographe" },
      { code: "244.146", intitule: "Rouleuse mécanique" },
      { code: "244.147", intitule: "Scanner" },
      { code: "244.148", intitule: "Scie" },
      { code: "244.149", intitule: "Seau en plastique" },
      { code: "244.150", intitule: "Sécateur" },
      { code: "244.151", intitule: "Serre joint" },
      { code: "244.152", intitule: "Servante" },
      { code: "244.153", intitule: "Spatule en bois" },
      { code: "244.154", intitule: "Squelette observation" },
      { code: "244.155", intitule: "Stroboscope" },
      { code: "244.156", intitule: "Surpresseur" },
      { code: "244.157", intitule: "Système biométrique" },
      { code: "244.158", intitule: "Table de soudure" },
      { code: "244.159", intitule: "Tableau" },
      { code: "244.160", intitule: "Table-banc" },
      { code: "244.161", intitule: "Tonneau" },
      { code: "244.162", intitule: "Toupie" },
      { code: "244.163", intitule: "Touret" },
      { code: "244.164", intitule: "Tourniqué hydraulique" },
      { code: "244.165", intitule: "Tours" },
      { code: "244.166", intitule: "Transpalette" },
      { code: "244.167", intitule: "Trépieds laboratoire" },
      { code: "244.168", intitule: "Truelle" },
      { code: "244.169", intitule: "Valise à transformateur" },
      { code: "244.170", intitule: "Vase communicant" },
      { code: "244.171", intitule: "Vidangeur" },
      { code: "244.172", intitule: "Voltmètre" },
      { code: "244.173", intitule: "Voyeuse" },
      {
        code: "244.174",
        intitule: "Machine et équipement de potabilisation d'eau",
      },
      { code: "244.175", intitule: "Agitateur" },
      { code: "244.176", intitule: "Amplificateur de brillance" },
      { code: "244.177", intitule: "Ambulance" },
      {
        code: "244.178",
        intitule: "Analyseur (de gaz, de sang, de seuil)",
      },
      { code: "244.179", intitule: "Angiographie" },
      { code: "244.180", intitule: "Appareil Biochimie NFS" },
      {
        code: "244.181",
        intitule: "Appareil d'hémocontrol (Hémocu)",
      },
      { code: "244.182", intitule: "Appareil de dépistage mobile" },
      { code: "244.183", intitule: "Appareil de radiographie" },
      { code: "244.184", intitule: "Appareil de réanimation" },
      {
        code: "244.185",
        intitule:
          "Appareil médico-dentaire (amalgameur, détartreur mobile, développeuse, etc.)",
      },
      { code: "244.186", intitule: "Appareil polymérisant" },
      { code: "244.187", intitule: "Armoire à médicaments" },
      { code: "244.188", intitule: "Aspirateur médical" },
      { code: "244.189", intitule: "Assistant muet" },
      { code: "244.190", intitule: "Audiomètre" },
      {
        code: "244.191",
        intitule: "Autoclave (de paillasse, mécanique, vertical)",
      },
      { code: "244.192", intitule: "Auto-kerato-refractomètre" },
      { code: "244.193", intitule: "Automate" },
      { code: "244.194", intitule: "Autoscope" },
      { code: "244.195", intitule: "Baie d'électrophysiologie" },
      { code: "244.196", intitule: "Bain marie" },
      {
        code: "244.197",
        intitule:
          "Balance (simple, avec échelle, à toise, électronique, etc.)",
      },
      {
        code: "244.198",
        intitule: "Berceaux (à coque, à enfant, GM, PM, etc.)",
      },
      { code: "244.199", intitule: "Bistouri" },
      { code: "244.200", intitule: "Blood rouler" },
      { code: "244.201", intitule: "Boîte (chirurgicales)" },
      { code: "244.202", intitule: "Boîte isotherme" },
      { code: "244.203", intitule: "Bouteille d'oxygène" },
      { code: "244.204", intitule: "Brancard de transport-civière" },
      { code: "244.205", intitule: "Bride à moufle" },
      { code: "244.206", intitule: "Cellule de Mallassiez" },
      { code: "244.207", intitule: "Centrifugeuse" },
      { code: "244.208", intitule: "Chaîne d'électrophorèse" },
      { code: "244.209", intitule: "Chaîne Elisa" },
      { code: "244.210", intitule: "Chaise roulante" },
      { code: "244.211", intitule: "Champ visuel de Goldman" },
      { code: "244.212", intitule: "Chargeur de pipette électronique" },
      { code: "244.213", intitule: "Chariot d'anesthésie" },
      {
        code: "244.214",
        intitule: "Chariot de soins, de nettoyage, de transport, etc.",
      },
      {
        code: "244.215",
        intitule: "Colonne (d'endoscopie, de célioscope)",
      },
      { code: "244.216", intitule: "Colposcope" },
      { code: "244.217", intitule: "Compresseur d'air" },
      { code: "244.218", intitule: "Compteur de cellules" },
      { code: "244.219", intitule: "Couveuse" },
      { code: "244.220", intitule: "Cruches" },
      { code: "244.221", intitule: "Cuve de migration" },
      { code: "244.222", intitule: "Décongélateur" },
      { code: "244.223", intitule: "Défibrillateur" },
      { code: "244.224", intitule: "Déminéralisateur mural" },
      { code: "244.225", intitule: "Détecteur de Pool Fœtal" },
      { code: "244.226", intitule: "Diathermie" },
      { code: "244.227", intitule: "Distillateur" },
      { code: "244.228", intitule: "Distributeur de paraffine" },
      { code: "244.229", intitule: "Divan d'examen" },
      { code: "244.230", intitule: "Doppler" },
      {
        code: "244.231",
        intitule: "Échelle d'acuité visuelle, de taille, etc.",
      },
      { code: "244.232", intitule: "Échographe" },
      {
        code: "244.233",
        intitule: "Électro cardiogramme (simple, d'effort, d'Olter)",
      },
      { code: "244.234", intitule: "Électro photomètre" },
      { code: "244.235", intitule: "Électroencéphalogramme" },
      { code: "244.236", intitule: "Électrothérapie + ultra son" },
      { code: "244.237", intitule: "Endoscopie" },
      { code: "244.238", intitule: "Ensemble gamma camera" },
      { code: "244.239", intitule: "Étuve" },
      {
        code: "244.240",
        intitule:
          "Fauteuil (consultation, soins, prélèvement, dentaire, dialyse etc.)",
      },
      { code: "244.241", intitule: "Four autoclave" },
      { code: "244.242", intitule: "Frontofocomètre" },
      { code: "244.243", intitule: "Générateur de dialyse" },
      { code: "244.244", intitule: "Glacière pharmacie" },
      { code: "244.245", intitule: "Glucomètre" },
      { code: "244.246", intitule: "Goagulometre à quatre (4) canaux" },
      { code: "244.247", intitule: "Groupe d'air et de vides" },
      { code: "244.248", intitule: "Hemoleucometre" },
      { code: "244.249", intitule: "Histokinette" },
      { code: "244.250", intitule: "Hotte à flux laminaire" },
      { code: "244.251", intitule: "Hystéromètre" },
      { code: "244.252", intitule: "Impédancemètre" },
      { code: "244.253", intitule: "Imprimante de labo" },
      { code: "244.254", intitule: "Incubateur" },
      { code: "244.255", intitule: "Injecteur" },
      { code: "244.256", intitule: "Insufflateur" },
      { code: "244.257", intitule: "IRM" },
      {
        code: "244.258",
        intitule:
          "Kit (de planning familial, réanimation, glucomètre etc.)",
      },
      {
        code: "244.259",
        intitule:
          "Lampes (à fente, opératoires ou scialytiques, d'examen, de photothérapie etc.)",
      },
      { code: "244.260", intitule: "Laryngoscope" },
      { code: "244.261", intitule: "Laser" },
      { code: "244.262", intitule: "Lavabo aseptique" },
      { code: "244.263", intitule: "Lave globule" },
      { code: "244.264", intitule: "Laveurs de microplaques" },
      { code: "244.265", intitule: "Lit d'hôpital et matelas" },
      { code: "244.266", intitule: "Loupe" },
      { code: "244.267", intitule: "Mammographe" },
      { code: "244.268", intitule: "Manomètre d'oxygène" },
      { code: "244.269", intitule: "Matériel d'AMU" },
      { code: "244.270", intitule: "Matériel d'IUPP" },
      {
        code: "244.271",
        intitule: "Meuble de consultation (ORL, ophtalmo, etc.)",
      },
      { code: "244.272", intitule: "Micropipette" },
      { code: "244.273", intitule: "Microscope" },
      { code: "244.274", intitule: "Moniteur de surveillance" },
      { code: "244.275", intitule: "Moteur chirurgical" },
      { code: "244.276", intitule: "Négatoscope" },
      { code: "244.277", intitule: "Nutripompe" },
      { code: "244.278", intitule: "Ophtalmoscope" },
      {
        code: "244.279",
        intitule:
          "Ordinateur (de cardiologie, radiologies, d'encospie, de laboratoire etc.)",
      },
      { code: "244.280", intitule: "Oxymètre de pouls" },
      { code: "244.281", intitule: "Paillasse" },
      { code: "244.282", intitule: "Paravent a plombé" },
      { code: "244.283", intitule: "Pèse-bébé ; pèse-personne" },
      { code: "244.284", intitule: "Appareil de photothérapie" },
      {
        code: "244.285",
        intitule:
          "Pinces (à badigeon, à clapet, à cocher, à col, à dissèque, à servir, etc.)",
      },
      { code: "244.286", intitule: "Plaque d'opaline" },
      {
        code: "244.287",
        intitule:
          "Plateaux (grand modèle, moyen, petit, technique, etc.)",
      },
      { code: "244.288", intitule: "Pleurscope complet" },
      {
        code: "244.289",
        intitule: "Portoir (aiguille, bistouri, pour pipettes, etc.)",
      },
      { code: "244.290", intitule: "Potence (en bois, en fer)" },
      { code: "244.291", intitule: "Appareil de pouliethérapie" },
      { code: "244.292", intitule: "Pousse-seringue" },
      { code: "244.293", intitule: "Presse à plasma" },
      { code: "244.294", intitule: "Programmateur de spacemaker" },
      { code: "244.295", intitule: "Projecteur de test" },
      { code: "244.296", intitule: "Réfrigérateur et congélateur médicaux" },
      { code: "244.297", intitule: "Régloscope" },
      { code: "244.298", intitule: "Reprographe numérisé" },
      { code: "244.299", intitule: "Respirateur (simple, de transport)" },
      { code: "244.300", intitule: "Scanner" },
      { code: "244.301", intitule: "Scie oscillante" },
      { code: "244.302", intitule: "Soudeuse" },
      { code: "244.303", intitule: "Source de lumière" },
      { code: "244.304", intitule: "Spectrophotomètre" },
      {
        code: "244.305",
        intitule: "Stérilisateur (de salle, poupinels ou à chaleur sèches)",
      },
      { code: "244.306", intitule: "Stéthoscope obstétrical" },
      { code: "244.307", intitule: "Table d'anesthésie" },
      { code: "244.308", intitule: "Table de photothérapie" },
      { code: "244.309", intitule: "Table de réanimation" },
      { code: "244.310", intitule: "Table opératoire" },
      {
        code: "244.311",
        intitule:
          "Tables (d'examen ou de soins, gynéco, pansement, accouchement)",
      },
      { code: "244.312", intitule: "Tabouret médical" },
      { code: "244.313", intitule: "Tambour" },
      {
        code: "244.314",
        intitule: "Tensiomètre (électrique, électronique, mécanique)",
      },
      { code: "244.315", intitule: "Thermomètre" },
      { code: "244.316", intitule: "Toc cardiographe" },
      {
        code: "244.317",
        intitule: "Toise (bébé, adulte, crénas, en fer, etc.)",
      },
      { code: "244.318", intitule: "Trocart" },
      { code: "244.319", intitule: "Urit médicale" },
      { code: "244.320", intitule: "Valise de verres d'essai" },
      { code: "244.321", intitule: "Vibromasseur" },
      {
        code: "244.322",
        intitule:
          "Matériel et équipement des laboratoires des Écoles et Universités",
      },
      { code: "244.323", intitule: "Alimentation stabilisée" },
      { code: "244.324", intitule: "Amplificateur" },
      { code: "244.325", intitule: "Analyseur de spectre" },
      { code: "244.326", intitule: "Appareil de mesure" },
      { code: "244.327", intitule: "Armoire d'alimentation" },
      { code: "244.328", intitule: "Autocom" },
      { code: "244.329", intitule: "Baie" },
      {
        code: "244.330",
        intitule: "Banc de mesure (numérique, analogique, etc.)",
      },
      {
        code: "244.331",
        intitule:
          "Base intercom (4 boitiers, clear com, 6 boitiers, etc.)",
      },
      { code: "244.332", intitule: "Batterie de musique" },
      { code: "244.333", intitule: "Bonnette pour micro" },
      { code: "244.334", intitule: "Cabine" },
      { code: "244.335", intitule: "Car de reportage" },
      { code: "244.336", intitule: "Carte mémoire SD" },
      { code: "244.337", intitule: "Casque d'écoute" },
      { code: "244.338", intitule: "Charge fictive" },
      { code: "244.339", intitule: "Chargeur de batterie" },
      { code: "244.340", intitule: "Chroma key" },
      { code: "244.341", intitule: "Clavier" },
      { code: "244.342", intitule: "Clé à connexion" },
      { code: "244.343", intitule: "Codeur" },
      {
        code: "244.344",
        intitule: "Coffrets frames Console (audio, de mixage)",
      },
      { code: "244.345", intitule: "Collier pour microphone" },
      { code: "244.346", intitule: "Commutateur" },
      { code: "244.347", intitule: "Compresseur" },
      { code: "244.348", intitule: "Connecteur" },
      { code: "244.349", intitule: "Contrôle retour Antenne" },
      { code: "244.350", intitule: "Coupleur" },
      { code: "244.351", intitule: "DFS 300 à voies" },
      { code: "244.352", intitule: "Dipôle radio" },
      { code: "244.353", intitule: "Distorsiomètre" },
      { code: "244.354", intitule: "Égaliseur graphique" },
      { code: "244.355", intitule: "Émetteur" },
      { code: "244.356", intitule: "Émetteur/récepteur" },
      { code: "244.357", intitule: "Enceinte acoustique" },
      { code: "244.358", intitule: "Enregistreur" },
      { code: "244.359", intitule: "Ensemble (sonorisation, lumière)" },
      { code: "244.360", intitule: "Extension NAS" },
      { code: "244.361", intitule: "Faisceau" },
      { code: "244.362", intitule: "Fréquencemètre" },
      {
        code: "244.363",
        intitule: "Générateur (caractère, signaux, etc.)",
      },
      {
        code: "244.364",
        intitule: "Grille (commutation de signaux, distribution, etc.)",
      },
      { code: "244.365", intitule: "Haut-parleur écoute" },
      { code: "244.366", intitule: "Horloge LED DIGITAL" },
      {
        code: "244.367",
        intitule:
          "IBM Works station MT-M6218-5GY avec logiciel NETIA 7.5",
      },
      { code: "244.368", intitule: "Insert téléphonique" },
      {
        code: "244.369",
        intitule: "Interface (audio, contrôle on air, etc.)",
      },
      { code: "244.370", intitule: "Investisseur" },
      { code: "244.371", intitule: "Lampe portative" },
      {
        code: "244.372",
        intitule: "Lecteur (CD, DAT, enregistreur, graveur, etc.)",
      },
      { code: "244.373", intitule: "Limiteur compresseur" },
      { code: "244.374", intitule: "Lot de carte I/O" },
      { code: "244.375", intitule: "Loupe éclairante" },
      { code: "244.376", intitule: "Magnétoscope" },
      {
        code: "244.377",
        intitule: "Malette (coffret pour connectiques, à outil, etc.)",
      },
      { code: "244.378", intitule: "Matrix de communication" },
      { code: "244.379", intitule: "Mélangeur" },
      {
        code: "244.380",
        intitule: "Mesureur (de champ, de terre)",
      },
      { code: "244.381", intitule: "Micro (filaire, à main, cravate, etc.)" },
      { code: "244.382", intitule: "Mini chaine" },
      { code: "244.383", intitule: "Mini enceinte pour PFL" },
      { code: "244.384", intitule: "Mixer audio" },
      { code: "244.385", intitule: "Mixette" },
      { code: "244.386", intitule: "Module ampli correcteur de ligne" },
      {
        code: "244.387",
        intitule:
          "Moniteur (audio actif stéréo, contrôle, baie de contrôle, vidéo, etc.)",
      },
      {
        code: "244.388",
        intitule: "Monitoring (audio, vidéo, retour plateau, etc.)",
      },
      { code: "244.389", intitule: "Multi transcodeur" },
      { code: "244.390", intitule: "Mur de moniteur" },
      { code: "244.391", intitule: "Onduleur" },
      { code: "244.392", intitule: "Paire d'enceintes de monitoring" },
      { code: "244.393", intitule: "Panneau de contrôle" },
      { code: "244.394", intitule: "Passerelle" },
      {
        code: "244.395",
        intitule:
          "Pied (de sol pour microphone, de table pour microphone, etc.)",
      },
      { code: "244.396", intitule: "Plateau" },
      { code: "244.397", intitule: "Post-production" },
      { code: "244.398", intitule: "Pylône" },
      { code: "244.399", intitule: "Rack" },
      {
        code: "244.400",
        intitule: "Récepteur (FM, multi bande, etc.)",
      },
      { code: "244.401", intitule: "Réémetteur" },
      { code: "244.402", intitule: "Régulateur" },
      { code: "244.403", intitule: "Report phone" },
      { code: "244.404", intitule: "Sélecteur des sources" },
      { code: "244.405", intitule: "Soldyne" },
      { code: "244.406", intitule: "Soupleur" },
      { code: "244.407", intitule: "Stabilisateur de tension" },
      { code: "244.408", intitule: "Station de travail" },
      { code: "244.409", intitule: "Station infographie PC" },
      { code: "244.410", intitule: "Synthétiseur d'écriture Title box" },
      {
        code: "244.411",
        intitule: "Système (d'écoute, intercom, clear com, etc.)",
      },
      {
        code: "244.412",
        intitule: "Table bâtie équipée de prises électriques",
      },
      { code: "244.413", intitule: "Talkie-Walkie" },
      { code: "244.414", intitule: "Tête de fibre optique" },
      { code: "244.415", intitule: "Tour de gravure" },
      { code: "244.416", intitule: "Touret de câble" },
      { code: "244.417", intitule: "Tourne disque" },
      { code: "244.418", intitule: "Transfo/isolateur" },
      { code: "244.419", intitule: "Tuner" },
      { code: "244.420", intitule: "Unité de gestion des commandes" },
      { code: "244.421", intitule: "Wattmètre" },
      { code: "244.422", intitule: "Caméras" },
      { code: "244.423", intitule: "Décodeur" },
      { code: "244.424", intitule: "Drone" },
      { code: "244.425", intitule: "Editing à 3 voies" },
      { code: "244.426", intitule: "Parabole" },
      { code: "244.427", intitule: "Post-production" },
      { code: "244.428", intitule: "Projecteur" },
      {
        code: "244.429",
        intitule: "Pupitre mélangeur vidéo, audio, etc.",
      },
      { code: "244.430", intitule: "Télécommande ralenti" },
      { code: "244.431", intitule: "Téléprompteur" },
      { code: "244.432", intitule: "Voies et contrôle de caméras" },
      { code: "244.433", intitule: "Logiciel de montage, de production" },
      { code: "244.434", intitule: "Mesureur de champ" },
      { code: "244.435", intitule: "Balance" },
      { code: "244.436", intitule: "Barrière automatique" },
      { code: "244.437", intitule: "Bascule" },
      { code: "244.438", intitule: "Brouette" },
      { code: "244.439", intitule: "Caisse à outils" },
      { code: "244.440", intitule: "Compresseur" },
      { code: "244.441", intitule: "Concasseur à marteau" },
      { code: "244.442", intitule: "Conteneur" },
      { code: "244.443", intitule: "Cuve" },
      { code: "244.444", intitule: "Diable" },
      { code: "244.445", intitule: "Enclume" },
      { code: "244.446", intitule: "Fondeuse" },
      { code: "244.447", intitule: "Glacière" },
      { code: "244.448", intitule: "GPS" },
      { code: "244.449", intitule: "Jumelles" },
      { code: "244.450", intitule: "Kiosque" },
      { code: "244.451", intitule: "Machines-outils de travail" },
      { code: "244.452", intitule: "Marmite" },
      { code: "244.453", intitule: "Micro moulinet" },
      { code: "244.454", intitule: "Minuterie modulaire" },
      { code: "244.455", intitule: "Moteur de lavage des engins" },
      { code: "244.456", intitule: "Paillasse" },
      { code: "244.457", intitule: "Palan" },
      { code: "244.458", intitule: "Pelle niveleuse" },
      { code: "244.459", intitule: "Pèse-essieux" },
      { code: "244.460", intitule: "Pompe à carburant" },
      { code: "244.461", intitule: "Poste de démonstration triphasé" },
      { code: "244.462", intitule: "Presse hydraulique" },
      { code: "244.463", intitule: "Régulateur de charge" },
      { code: "244.464", intitule: "Régulateur de vide mural" },
      { code: "244.465", intitule: "Station de sondage" },
      { code: "244.466", intitule: "Station pour graphisme et montage" },
      { code: "244.467", intitule: "Station totale avec accessoires" },
      { code: "244.468", intitule: "Suppresseur d'eau" },
      { code: "244.469", intitule: "Table traçante" },
      { code: "244.470", intitule: "Table de travail (ateliers)" },
      { code: "244.471", intitule: "Tente pliante, parasol" },
      { code: "244.472", intitule: "Transformateur" },
      { code: "244.473", intitule: "Tronçonneuse" },
      {
        code: "244.474",
        intitule: "Matériel et outillage des travaux publics",
      },
      { code: "244.475", intitule: "Abreuvoir, auge, mangeoire" },
      { code: "244.476", intitule: "Arrosoir" },
      { code: "244.477", intitule: "Bacs à eau" },
      { code: "244.478", intitule: "Batteuse" },
      { code: "244.479", intitule: "Botteleuse" },
      { code: "244.480", intitule: "Boussole" },
      { code: "244.481", intitule: "Broyeur" },
      { code: "244.482", intitule: "Cage à veau" },
      { code: "244.483", intitule: "Camera trappe" },
      { code: "244.484", intitule: "Chariot à aliment" },
      { code: "244.485", intitule: "Charrette" },
      { code: "244.486", intitule: "Charrue" },
      { code: "244.487", intitule: "Clinomètre" },
      { code: "244.488", intitule: "Compact forestier" },
      { code: "244.489", intitule: "Coupe foin" },
      { code: "244.490", intitule: "Couveuses" },
      { code: "244.491", intitule: "Décompacteur" },
      { code: "244.492", intitule: "Décortiqueuse" },
      { code: "244.493", intitule: "Détecteur d'élément nucléaire" },
      { code: "244.494", intitule: "Détecteur d'élément radio actif" },
      { code: "244.495", intitule: "Égraineuse" },
      { code: "244.496", intitule: "Épandeur" },
      { code: "244.497", intitule: "Foreur/foreuse" },
      { code: "244.498", intitule: "Marteau-piqueur" },
      { code: "244.499", intitule: "Moissonneuse-batteuse" },
      { code: "244.500", intitule: "Moteur réducteur" },
      { code: "244.501", intitule: "Moteur synchrone" },
      { code: "244.502", intitule: "Moteur thermique" },
      { code: "244.503", intitule: "Moto pompe" },
      { code: "244.504", intitule: "Peson" },
      { code: "244.505", intitule: "Pivot d'irrigation" },
      { code: "244.506", intitule: "Podomètre" },
      { code: "244.507", intitule: "Pompe immergée" },
      { code: "244.508", intitule: "Pulvérisateur" },
      { code: "244.509", intitule: "Rame d'irrigation" },
      { code: "244.510", intitule: "Ruche" },
      { code: "244.511", intitule: "Semoir" },
      { code: "244.512", intitule: "Station de pompage" },
      { code: "244.513", intitule: "Télémètre" },
      { code: "244.514", intitule: "Télescope" },
      { code: "244.515", intitule: "Tondeuse" },
      { code: "244.516", intitule: "Topo-file" },
      { code: "244.517", intitule: "Tracteur" },
      { code: "244.518", intitule: "Trieuse" },
      { code: "244.519", intitule: "Vibroculteur" },
      {
        code: "244.999",
        intitule: "Autres matériels et outillages techniques",
      },
    ],
  },
  {
    compte: "245",
    libelle: "MATÉRIEL DE TRANSPORT EN COMMUN ET DE MARCHANDISES",
    categorie: "Mobilier et équipements",
    famille: "Transport collectif",
    type_bien: "immobilisation",
    items: [
      { code: "245.001", intitule: "Avion" },
      { code: "245.002", intitule: "Bateau" },
      { code: "245.003", intitule: "Bus, minibus" },
      { code: "245.004", intitule: "Camion" },
      { code: "245.005", intitule: "Camionnette" },
      { code: "245.006", intitule: "Car" },
      { code: "245.007", intitule: "Caravane" },
      { code: "245.008", intitule: "Hélicoptère" },
      { code: "245.009", intitule: "Métro / Trame" },
      { code: "245.010", intitule: "Pirogue" },
      { code: "245.011", intitule: "Train" },
      { code: "245.012", intitule: "Tricycle" },
      { code: "245.013", intitule: "Vagon" },
      { code: "245.014", intitule: "Voiture" },
      {
        code: "245.999",
        intitule:
          "Autres matériels de transport en commun et de marchandises",
      },
    ],
  },
  {
    compte: "246",
    libelle: "COLLECTIONS - ŒUVRES D'ART",
    categorie: "Mobilier et équipements",
    famille: "Collections et art",
    type_bien: "immobilisation",
    items: [
      { code: "246.001", intitule: "Trophée" },
      { code: "246.002", intitule: "Peinture" },
      { code: "246.003", intitule: "Sculpture" },
      { code: "246.004", intitule: "Objet de l'antiquité" },
      { code: "246.005", intitule: "Objet de collection" },
      { code: "246.006", intitule: "Tableau" },
      { code: "246.007", intitule: "Portrait officiel (PR, PM, etc.)" },
      { code: "246.999", intitule: "Autres collections et œuvres d'art" },
    ],
  },
  {
    compte: "247",
    libelle: "CHEPTELS",
    categorie: "Mobilier et équipements",
    famille: "Animaux",
    type_bien: "immobilisation",
    items: [
      { code: "248.001", intitule: "Âne" },
      { code: "248.002", intitule: "Animal des zoos" },
      { code: "248.003", intitule: "Bœuf" },
      { code: "248.004", intitule: "Vache" },
      { code: "248.005", intitule: "Taureau" },
      { code: "248.006", intitule: "Veau" },
      { code: "248.007", intitule: "Mouton" },
      { code: "248.008", intitule: "Chèvre" },
      { code: "248.009", intitule: "Porc" },
      { code: "248.010", intitule: "Cheval" },
      { code: "248.011", intitule: "Chameau" },
      { code: "248.012", intitule: "Dromadaire" },
      { code: "248.013", intitule: "Chien" },
      { code: "248.014", intitule: "Chat" },
      { code: "248.015", intitule: "Lapin" },
      { code: "248.016", intitule: "Abeille" },
      { code: "248.999", intitule: "Autres cheptels" },
    ],
  },
  {
    compte: "249",
    libelle:
      "AUTRES ACQUISITIONS ET GROSSES RÉPARATIONS DU MATÉRIEL ET MOBILIER",
    categorie: "Mobilier et équipements",
    famille: "Autres matériels",
    type_bien: "immobilisation",
    items: [
      {
        code: "249.999",
        intitule:
          "Autres acquisitions et grosses réparations du matériel et mobilier",
      },
    ],
  },
];

// Statistiques utiles
export const STATS_PARTIE_A = {
  total_groupes: PARTIE_A_IMMOBILISATIONS.length,
  total_items: PARTIE_A_IMMOBILISATIONS.reduce(
    (acc, g) => acc + g.items.length,
    0
  ),
  comptes: PARTIE_A_IMMOBILISATIONS.map((g) => g.compte),
};
